### ISSUE TITLE
`npm run build:both` hangs

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [reduxify/seedux#80]
I get the following error then a hang when I run `npm run build:both` (to be clear, this is after an `npm install`):

```
maciek@mothra:~/code/aux/seedux$ npm run build:both

> seedux@0.0.8 build:both /home/maciek/code/aux/seedux
> webpack -w --config extension-webpack.config.js | webpack -w --config library-webpack.config.js

Hash: 33d663b038c70df097d5
Version: webpack 1.14.0
Time: 2674ms
   Asset    Size  Chunks             Chunk Names
index.js  253 kB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
    + 69 hidden modules

ERROR in ./lib/redux/src/createStore.js
Module not found: Error: Cannot resolve module 'symbol-observable' in /home/maciek/code/aux/seedux/lib/redux/src
 @ ./lib/redux/src/createStore.js 16:24-52
```

A gdb backtrace shows this:

```
(gdb) bt
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x0000000001327fca in uv__epoll_wait (epfd=<optimized out>, events=events@entry=0x7ffe4749b1b0, nevents=nevents@entry=1024, timeout=timeout@entry=50) at ../deps/uv/src/unix/linux-syscalls.c:321
#2  0x0000000001325fdb in uv__io_poll (loop=loop@entry=0x1de7d00 <default_loop_struct>, timeout=50) at ../deps/uv/src/unix/linux-core.c:271
#3  0x00000000013166b6 in uv_run (loop=0x1de7d00 <default_loop_struct>, mode=UV_RUN_ONCE) at ../deps/uv/src/unix/core.c:354
#4  0x00000000010a2fe0 in node::Start(int, char**) ()
#5  0x00007f9be0af3830 in __libc_start_main (main=0x7b4ce0 <main>, argc=4, argv=0x7ffe4749e638, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe4749e628) at ../csu/libc-start.c:291
#6  0x00000000007b4f6d in _start ()
```

Not much CPU usage at this point. Any ideas? I do get a warning from `npm install`, but it does imply the dependency here is optional:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

**Comment by mlampedx** [comment]
Hi Maciek! Thanks for reporting this error. A quick potential fix could be to navigate into the seedux/lib/redux directory and explicitly run 'npm install symbol-observable.' I have encountered a similar issue where I had to explicitly run 'npm install' inside of the redux and react-redux directories since they are not packaged as sub-modules. I hope this helps! Please let us know if you continue to encounter this issue.

**Comment by uhoh-itsmaciek** [comment]
@mlampedx thanks, that seems to get rid of the error, but I still seem to hit the hang (with essentially the same backtrace as above).

**Comment by mlampedx** [comment]
Hi Maciek. I believe webpack watch mode (-w) is causing the illusion of a hang as it watches for changes to the codebase that it can re-transpile on the fly.

**Comment by uhoh-itsmaciek** [comment]
Ah, got it. That wasn't clear from the README. Maybe add both of these issues to the docs? I can submit a PR if you'd like.

**Comment by mlampedx** [comment]
Sure, I think it would be great if the README clarified that we are using the watch command for our non-production npm run build scripts and that the dispatch logger accounts for Immutable.js data structure properties under the hood. Happy to review any changes you think would be beneficial!

**Comment by mlampedx** [comment]
We have 'npm run build:both' set to watch for changes and
